#!/usr/bin/env python

import json
import jinja2
import os

templateLoader = jinja2.FileSystemLoader( searchpath="/" )
templateEnv = jinja2.Environment( loader=templateLoader )
TEMPLATE_FILE = os.path.dirname(os.path.realpath(__file__)) + "/template.jinja"
template = templateEnv.get_template( TEMPLATE_FILE )

json_data = open('./security_groups').read()
data = json.loads(json_data)

sgs = {}

print "---"
print "- name: Manage security groups"
print "  connection: local"
print "  hosts: 127.0.0.1"
print "  sudo: False"
print "  tasks:"

for sg in data["SecurityGroups"]:
    sgs[sg['GroupId']] = [sg['GroupName'], sg['Description']]

for sg in data["SecurityGroups"]:
    templateVars = { "sg" : sg, "sgs" : sgs }
    outputText = template.render( templateVars )
    print outputText
